config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"
  resources :books, only: [ :new, :create, :show, :index, :edit, :update, :destroy ]
  resources :users, only: [ :show,:index, :edit, :update ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 
 ## imageを使用可能にする
 has_one_attached :image
 
 ## 1:Nの子設定
 belongs_to :user
 
 ## バリテーション設定
 validates :title, presence: true
 validates :body, presence: true, length: { maximum: 200 }

 def get_image
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  image
 end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  ## パスワードの正確性
  devise :database_authenticatable,
  ## ユーザー登録、情報編集、削除
  :registerable,
  ## パスワードのリセット
  :recoverable,
  ## ログイン情報の保存
  :rememberable,
  ## バリテーション設定
  :validatable

  ## バリテーション設定
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: { case_sensitive: false }
  # validates :introduction, length: { maximum: 50 }
  validates :introduction, presence: false, length: { maximum: 50 }
  
  ## 1:Nの親設定
  has_many :books, dependent: :destroy
  
  ## プロフィール画像
  has_one_attached :profile_image
  
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  ## ログインしてない場合、topへ
  before_action :authenticate_user!, except: [:top, :about]
  
  ## コントローラー実行前に処理 =>  protected
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  ## フラッシュメッセージ
  add_flash_types :success, :info, :warning, :danger

  ## サインイン後のリダイレクト先
  def after_sign_in_path_for(resource)
    user_path(current_user[:id])
  end

  ## サインアウト後のリダイレクト先
  def after_sign_out_path_for(resource)
    "/"
  end

  ## 他コントローラからも参照
  protected

  def configure_permitted_parameters
    ## ユーザー登録時, nameデータ操作を許可
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :name, :email ])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  ## コントローラー実行前に処理。ログインユーザーが対象
  before_action :correct_user, only: [:edit, :update]

  ## 投稿データの保存
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book[:id]), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.new
    # 投稿ID取得
    @post = Book.find(params[:id])
    # 投稿データ内から投稿者IDを取得
    @user = User.find_by(id: @post.user_id)
    # モデル内の投稿者IDを絞り込み
    @books = Book.where(user_id: @post.user_id)
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: "have destroyed book successfully."
  end

  ## 投稿データのストロングパラメー
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def correct_user
    ## 投稿ID取得
    @post = Book.find(params[:id])
    ## 投稿データ内から投稿者IDを取得
    @user = User.find_by(id: @post.user_id)
    ## ログインユーザー以外ならBookindexへ
    redirect_to(books_path) unless @user == current_user
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  ## コントローラー実行前に処理。ストロングパラメーター参照
  before_action :correct_user, only: [:edit, :update]
  
  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    ## ユーザーIDで投稿を絞り込み
    @books = Book.where(user_id: params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

 private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def correct_user
    ## ユーザーID取得
    @user = User.find(params[:id])
    ## ログインユーザー以外ならBookindexへ
    redirect_to user_path(current_user) unless @user == current_user
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
<div id="error_explanation">
  <% if book.errors.any? %>
    <h3>
      <%= book.errors.count %> errors prohibited this obj from being saved:
    </h3>
    
    <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/books/_user_info.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag @user.get_profile_image(100,100), class: "attachment" %>
  
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
    	  <th>name</th>
    	  <th><%= @user.name %></th>
      </tr>
        
      <tr>
    	  <th>introduction</th>
    	  <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>
  
  <div class="row">
    <%= link_to edit_user_path, class: "btn btn-outline-secondary btn-block" do%>
      <i class="fa-solid fa-user-gear"></i>
    <% end %>
    
  </div>
  <h2 class="mt-3">New book</h2>
  
  <%= form_with model: @books do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, id: "book_title", class: "form-control book_title" %>
    </div>
    
    <div class="form-group">
      <%= f.label :Opinion %>
      <%= f.text_area :body, id: "book_body", class: "form-control book_body" %>
    </div>
    
    <div class="form-group">
    <%= f.submit "Create Book", class: "btn btn-success" %>
    </div>
  <% end %>
  
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		
  		<!--共通テンプレート エラー-->
  		<%= render partial: "books/error.html.erb", locals: { book: @book } %>
  
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, id: "book_title", class: "form-control book_title" %>
        </div>
        
        <div class="form-group">
          <%= f.label :Opinion %>
          <%= f.text_area :body, id: "book_body", class: "form-control book_body" %>
        </div>
        
        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
      <% end %>
      
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>    
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <!--共通テンプレート エラー-->
  <%= render partial: "books/error.html.erb", locals: { book: @book } %> 
  
  <div class="row">
    <!-- 共通テンプレート UserInfo-->
    <%= render partial: "users/user_info.html.erb", locals: { book: @book, user: current_user } %>
    
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        
        <tbody>
          <% @books.each do |post_image| %>
            <tr>
              <td>
                <!-- プロフィール画像 -->
                <%= link_to user_path(post_image.id)  do %>
                  <%= image_tag post_image.user.get_profile_image(40,40) %>
                <% end %>
              </td>
                
              <td>
                <%= link_to post_image.title, book_path(post_image.id) %>
              </td>
                
              <td>
                <%= post_image.body %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
 
  </div>
</div>

app/views/books/show.html.erb
<p id="notice"></p>

<div class="container px-5 px-sm-0">
  <div class="row">
      
    <!--共通テンプレート UserInfo-->
    <%= render partial: "users/user_info.html.erb",
    locals: { book: @book, user:  @user } %>
    
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
  
      <table class="table table-hover table-inverse">
        
        <tbody>
          <% @books.each do |post_image| %>
            <tr>
              <td>
                
                <%= link_to user_path(@user[:id]) do %>
                  <!-- プロフィール画像 -->
                  <%= image_tag post_image.user.get_profile_image(40,40), class: "attachment user profile_image fallback" %>
                  <br />
                  <%= post_image.user.name %>
                <% end %>
                
              </td>
                
              <td>
                <%= link_to post_image.title, book_path %>
              </td>
              
              <td>
                <%= post_image.body %>
              </td>
              
              <td>
                 <!-- 投稿者 = ログインユーザー-->
                 <% if @user == current_user %>
                  <%= link_to "Edit", edit_book_path(params[:id]), class: "btn btn-sm btn-success" %>
                <% end %>
              </td>
              
              <td>
                <!-- 投稿者 = ログインユーザー-->
                <% if @user == current_user %>
                  <%= link_to "Destroy", book_path(params[:id]), method: :delete,
                              "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-danger" %>
                <% end %>
              </td>
              
            </tr>
          <% end %>
        </tbody>
        
      </table>
    </div>
   
  </div>
</div>

app/views/homes/about.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up"%>
        </div>
      </div>
    
    </div>
  </div>
</div>

app/views/layouts/_flash_message.html.erb
<% flash.each do |key, value| %>
  <p id="notice" >
    <%= value %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <title>Bookers2</title>
  </head>

  <body>
    <% if user_signed_in? %>
      <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container">
            <%= link_to "/", class: "navbar-brand" do %>
              <span>Bookers</span>
            <% end %>
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              
              <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                
                
                  <li>
                    <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
                      <i class="fa-solid fa-house-chimney"></i>
                      Home
                    <% end %>
                  </li>
                  
                  <li>
                    <%= link_to users_path, class: "nav-link text-light" do %>
                      <i class="fa-solid fa-users"></i>
                      Users
                    <% end %>
                  </li>
                  
                  <li>
                    <%= link_to books_path, class: "nav-link text-light" do %>
                      <i class="fa-solid fa-book-open"></i>
                      Books
                    <% end %>
                  </li>
                  
                  <li>
                    <%= link_to  destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                      <i class="fa-solid fa-sign-out-alt"></i>
                      Log out
                    <% end %>
                  </li>
                
              </ul>
            </div>
            
          </div>
        </nav>
      </header>
    <% else %>
    
      <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container">
            <%= link_to "/", class: "navbar-brand" do %>
              <span>Bookers</span>
            <% end %>
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              
              <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                  
                  <li>
                    <%= link_to "/", class: "nav-link text-light" do %>
                      <i class="fa-solid fa-house-chimney"></i>
                      Home
                    <% end %>
                  </li>
                  
                  <li>
                    <%= link_to about_path, class: "nav-link text-light" do %>
                      <i class="fa-solid fa-link"></i>
                      About
                    <% end %>
                  </li>
                  
                  <li>
                    <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                      <i class="fa-solid fa-user-plus"></i>
                      Sign up
                    <% end %>
                  </li>
                  
                  <li>
                    <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                      <i class="fa-solid fa-sign-in-alt"></i>
                      Log in
                    <% end %>
                  </li>
                
              </ul>
            </div>
            
          </div>
        </nav>
      </header>
    <% end %>
    
    <main>
      <!-- 共通テンプレート フラッシュメッセージ -->
      <%= render "layouts/flash_message"%>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>

</html>

app/views/users/_user_info.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  
  <%= image_tag user.get_profile_image(100,100), class: "attachment user profile_image fallback" %>
      
  <table class="table">
    <tbody>
        <tr></tr>
        <tr>
      	  <th>name</th>
          <th><%= user.name %></th>
        </tr>
              
        <tr>
      	  <th>introduction</th>
      	  <th><%= user.introduction %></th>
        </tr>
    </tbody>
  </table>
      
  <div class="row">
    <%= link_to edit_user_path(user[:id]), class: "btn btn-outline-secondary btn-block" do%>
      <i class="fa-solid fa-user-gear"></i>
    <% end %>
  </div>
  
  <h2 class="mt-3">New book</h2>
  
  <%= form_with model: book do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, id: "book_title", class: "form-control book_title" %>
    </div>
    
    <div class="form-group">
      <%= f.label :Opinion %>
      <%= f.text_area :body, id: "book_body", class: "form-control book_body" %>
    </div>
    
    <div class="form-group">
      <%= f.submit "Create Book", class: "btn btn-success" %>
    </div>
  <% end %>
    
</div>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model: @user do |f| %>
  
        <!--共通テンプレート エラー-->
    		<%= render partial: "books/error.html.erb", locals: { book: @user } %>
    		<!--minimum is 2 characters-->
    		
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, id: "user_name", class: "form-control name" %>
        </div>
        
        <div class="form-group">
          <%= f.label :image %> <br />
          <%= f.file_field :profile_image, accept: "image/*" %>
        </div>
        
        <div class="form-group">
          <%= f.label :introduction %>
          <%= f.text_area :introduction, id: "user_introdution", class: "form-control introdution" %>
        </div>
        
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <!-- 共通テンプレート UserInfo-->
    <%= render partial: "users/user_info.html.erb", locals: { book: @book, user: @user } %>
    
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        
        <tbody>
          <% @users.each do |post_image| %>
            <tr>
              <td>
                <!-- プロフィール画像 -->
                <%= image_tag post_image.get_profile_image(40,40) %>
              </td>
                
              <td>
                <%= post_image.name %>
              </td>
                
              <td>
                <%= link_to "Show", user_path(post_image[:id]) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
</div>
 </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    
    <!-- 共通テンプレート UserInfo-->
    <%= render partial: "users/user_info.html.erb", locals: { book: @book, user: @user } %>
        
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
        </thead>
        
        <tbody>
          <% @books.each do |post_image| %>
            <tr>
              <td>
                <!-- プロフィール画像 -->
                <%= link_to user_path(@user[:id]) do %>
                  <%= image_tag @user.get_profile_image(50,50) %>
                <% end %>
              </td>
                
              <td>
                <!-- タイトル showリンク -->
                  <%= link_to post_image.title, book_path(post_image[:id]) %>
              </td>
                
              <td>
                <!-- 本文 -->
                <%= post_image.body %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
</div>
    
  </div>
</div>